SELECT * FROM coffee_shop.transactions;
-- 1. What is the total revenue generated from all coffee sales on a specific day?
SELECT 
    date, 
    SUM(money) AS total_revenue
FROM 
    coffee_shop.transactions
GROUP BY 
    date;
-- 2. How many transactions were made using cards versus other payment methods?
  SELECT 
    cash_type, 
    COUNT(*) AS Total_Transactions_cardvscash
FROM 
    coffee_shop.transactions
GROUP BY 
    cash_type;
    -- 3. What are the most popular types of coffee ordered?
         SELECT  
    coffee_name, 
    COUNT(*) AS Total
FROM 
    coffee_shop.transactions
GROUP BY 
    coffee_name
ORDER BY 
    Total DESC
    LIMIT 5;
    -- 4.Can you show a breakdown of total revenue by coffee type?
     SELECT coffee_name, sum(money) as Total_reveneue
     FROM 
    coffee_shop.transactions
    group by coffee_name
    order by sum(money) desc;
    
    -- 5. What is the average amount spent per transaction?
    
    select avg(money)  AvgM FROM 
    coffee_shop.transactions;
    -- 6. How many unique customers (based on card numbers) made purchases on a given day?
          select date, count(distinct(card)) as customers FROM 
    coffee_shop.transactions
    where cash_type ='card'
    group by date;
    
    -- 7.What is the highest and lowest transaction amount for each day?
      
     SELECT 
    date, 
    MAX(money) AS max_amount, 
    MIN(money) AS min_amount
FROM 
    coffee_shop.transactions
GROUP BY 
    date;
    
    -- 8. Can you list all transactions that were made after 5 PM?
         select * from coffee_shop.transactions
         where datetime > '17:00:00'
         order by datetime;
         
	-- 9. How many transactions were made for each coffee type on a particular date?
         
         select date,count(card) as Totaltransactions
         from coffee_shop.transactions
		group by date;
        
	-- 10. Which time of day (morning, afternoon, evening) generates the most sales?

   SELECT 
    SUM(money) AS most_sales,
    CASE
        WHEN TIME(datetime) < '12:00:00' THEN 'Morning'
        WHEN TIME(datetime) BETWEEN '12:00:00' AND '17:00:00' THEN 'Afternoon'
        ELSE 'Evening'
    END AS Timing
FROM 
    coffee_shop.transactions
GROUP BY 
    Timing
ORDER BY 
    most_sales DESC;
    -- 11. What is the total revenue generated by each unique customer?
    SELECT 
    card,  
    SUM(money) AS total_revenue
FROM 
    coffee_shop.transactions
GROUP BY 
    card;
  -- 12. Can you show the top 3 most expensive coffees sold based on transaction amounts?
        SELECT 
    coffee_name, 
    MAX(money) AS max_amount
FROM 
    coffee_shop.transactions
GROUP BY 
    coffee_name
ORDER BY 
    max_amount DESC
LIMIT 3;  
-- 13 How many coffees were sold between specific time intervals, e.g., between 12 PM and 3 PM?

 SELECT 
    COUNT(*) AS total_coffees_sold
FROM 
    coffee_shop.transactions
WHERE 
    TIME(datetime) BETWEEN '12:00:00' AND '15:00:00';